import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    `java-library`
    idea
    `maven-publish`
    alias(libs.plugins.kotlinJVM)
    alias(libs.plugins.kotlinSerial)
    alias(libs.plugins.neoForgedMDK)
}

version = modVersion
group = modGroup
base.archivesName = modId

// Mojang ships Java 21 to end users in 1.20.5+, so we set JVM target version to 21.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

// Sets Kotlin compiler version same as JVM target version.
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_21)
    }
}

// Configures neoForge environment settings.
neoForge {
    version = neoforgedVersion
    parchment {
        mappingsVersion = parchmentVersion
        minecraftVersion = parchmentMcVersion
    }

    // If the mod needs Access Transformer (AT), put it here.

    runs {
        configureEach {
            systemProperty("forge.logging.markers", "REGISTRIES")
            logLevel = org.slf4j.event.Level.DEBUG
        }

        register("client") {
            client()
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        register("server") {
            server()
            programArgument("--nogui")
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        register("gameTestServer") {
            type = "gameTestServer"
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        register("data") {
            data()
            programArguments.addAll("--mod", modId, "--all",
                                    "--output", file("src/generated/resources/").absolutePath,
                                    "--existing", file("src/main/resources/").absolutePath)
        }
    }

    mods {
        create(modId) {
            sourceSet(sourceSets.main.get())
        }
    }
}

// Include resources generated by data generators and supported language mixing.
sourceSets {
    main {
        java {
            srcDir("src/main/java")
        }
        kotlin {
            srcDir("src/main/kotlin")
        }
        resources {
            srcDir("src/generated/resources")
        }
    }
}

// Sets up a dependency configuration called 'localRuntime'.
@Suppress("UnstableApiUsage")
configurations {
    val runtimeClasspath by getting
    create("localRuntime") {
        runtimeClasspath.extendsFrom(this)
    }
}

repositories()

dependencies {
    // Kotlin for Forge 5.5.0
    implementation(libs.kotlinForForge)

    // JEI 19.25.0.323
    compileOnly(libs.jeiBaseAPI)
    compileOnly(libs.jeiNeoforgedAPI)
    runtimeOnly(libs.jei)
}

tasks.withType<ProcessResources> {
    val replaceProperties = mapOf(
        "minecraft_version" to mcVersion,
        "minecraft_version_range" to mcVersionRange,
        "neo_version" to neoforgedVersion,
        "neo_version_range" to neoforgedVersionRange,
        "loader_version_range" to modLoaderVersionRange,
        "mod_id" to modId,
        "mod_name" to modName,
        "mod_license" to modLicense,
        "mod_version" to modVersion,
        "mod_authors" to modAuthors,
        "mod_description" to modDescription,
        "mod_credits" to modCredits
    )

    inputs.properties(replaceProperties)

    filesMatching("META-INF/neoforge.mods.toml") {
        expand(replaceProperties)
    }
}

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }
    repositories {
        maven {
            url = uri("file://${project.projectDir}/repo")
        }
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8" // Use the UTF-8 charset for Java compilation
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        isDownloadSources = true
        isDownloadJavadoc = true
    }
}