# Gradle Settings
org.gradle.jvmargs=-Xmx2G
org.gradle.caching=true
org.gradle.java.home=C:/Users/86199/.jdks/azul-21.0.10

# Mod Info
modGroup = examplemod
modId = examplemod
modName = Example Mod
modVersion = 1.0.0

# Minecraft Info
mcVersion = 1.12.2
userName = Magic_Sweepy

coreModPluginPath = examplemod.mixins.ExampleMixinLoadingPlugin
generateTokenPath = examplemod.ExampleModTags

# Shadow Configurations
useShadowDeps = true
minimizeShadowedDependencies = false
relocateShadowedDependencies = false
shadowRelocationPrefix =
