# Gradle Settings
org.gradle.jvmargs=-Xmx2G
org.gradle.caching=true

# Mod Info
modGroup = examplemod
modId = examplemod
modName = Example Mod
modVersion = 1.0.0

# Minecraft Info
mcVersion = 1.12.2
userName = Magic_Sweepy

coreModPluginPath = examplemod.mixins.ExampleMixinLoadingPlugin
generateTokenPath = examplemod.ExampleModTags

# Shadow Configurations
useShadowDeps = false
minimizeShadowedDependencies = false
relocateShadowedDependencies = false
shadowRelocationPrefix =
