import org.gradle.kotlin.dsl.provideDelegate
import java.time.ZonedDateTime
import java.time.format.DateTimeFormatter
import kotlin.reflect.KProperty

plugins {
    id("scala")
    id("idea")
    id("maven-publish")
    alias(libs.plugins.modDevKit)
}

// region Environment Info

val Project.mcVersion by StringDelegate()
val Project.mcVersionRange by StringDelegate()
val Project.neoForgedVersion by StringDelegate()
val Project.neoForgedVersionRange by StringDelegate()
val Project.parchmentVersion by StringDelegate()
val Project.parchmentMcVersion by StringDelegate()
val Project.modLoaderVersionRange by StringDelegate()

// endregion

// region Mod Info

val Project.modId by StringDelegate()
val Project.modName by StringDelegate()
val Project.modGroup by StringDelegate()
val Project.modVersion by StringDelegate()
val Project.modAuthors by StringDelegate()
val Project.modLicense by StringDelegate()
val Project.modDescription by StringDelegate()
val Project.modCredits by StringDelegate()

// endregion

version = modVersion
group = modGroup
base.archivesName = modId

// Mojang ships Java 21 to end users in 1.20.5+, so we set JVM target version to 21.
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = neoForgedVersion
    parchment {
        mappingsVersion = parchmentVersion
        minecraftVersion = parchmentMcVersion
    }

    // If the mod needs Access Transformer (AT), put it here.
    // ...

    runs {
        configureEach {
            systemProperty("forge.logging.markers", "REGISTRIES")
            logLevel = org.slf4j.event.Level.DEBUG
        }

        register("client") {
            client()
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        register("server") {
            server()
            programArgument("--nogui")
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        register("gameTestServer") {
            type = "gameTestServer"
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        register("data") {
            data()
            programArguments.addAll("--mod", modId, "--all",
                                    "--output", file("src/generated/resources/").absolutePath,
                                    "--existing", file("src/main/resources/").absolutePath)
        }
    }

    mods {
        create(modId) {
            sourceSet(sourceSets.main.get())
        }
    }
}

// Include resources generated by data generators and supported language mixing.
sourceSets.main {
    resources {
        srcDir("src/generated/resources")
    }
}

@Suppress("UnstableApiUsage")
configurations {
    findByName("localRuntime")?.let {
        runtimeClasspath {
            extendsFrom(it)
        }
    }
}


repositories {
    mavenCentral()
    gradlePluginPortal()
    maven {
        name = "Curse Maven"
        url = uri("https://cursemaven.com")
    }
    maven {
        name = "Kotori316 Maven"
        url = uri("https://maven.kotori316.com")
        content {
            includeGroup("com.kotori316")
            includeGroup("org.typelevel")
        }
    }
    maven {
        name = "Blamejared Maven"
        url = uri("https://maven.blamejared.com/")
        content {
            includeGroup("mezz.jei")
        }
    }
}


dependencies {
    // region Language Provider

    val scalableCats = variantOf(libs.scalableCats) { classifier("with-library") }
    runtimeOnly(scalableCats) { isTransitive = false }
    jarJar(scalableCats) { isTransitive = false }

    compileOnly(libs.scala)
    compileOnly(libs.scala3)
    compileOnly(libs.cats)

    // endregion

    // region Mod Dependencies

    compileOnly(libs.jeiBaseAPI)
    compileOnly(libs.jeiNeoforgedAPI)
    runtimeOnly(libs.jei)

    // endregion
}

tasks.withType<ProcessResources> {
    val replaceProperties = mapOf(
        "minecraft_version"       to mcVersion,
        "minecraft_version_range" to mcVersionRange,
        "neo_version"             to neoForgedVersion,
        "neo_version_range"       to neoForgedVersionRange,
        "loader_version_range"    to modLoaderVersionRange,
        "mod_id"                  to modId,
        "mod_name"                to modName,
        "mod_license"             to modLicense,
        "mod_version"             to modVersion,
        "mod_authors"             to modAuthors,
        "mod_description"         to modDescription,
        "mod_credits"             to modCredits)

    inputs.properties(replaceProperties)

    filesMatching("META-INF/neoforge.mods.toml") {
        expand(replaceProperties)
    }
}

// Manifest for reading at runtime.
tasks.withType<Jar> {
    manifest {
        attributes(
            mapOf(
                "Specification-Title"      to modId,
                "Specification-Vendor"     to modAuthors,
                "Specification-Version"    to "1",
                "Implementation-Title"     to project.name,
                "Implementation-Version"   to project.tasks.jar.get().archiveVersion,
                "Implementation-Vendor"    to modAuthors,
                "Implementation-Timestamp" to ZonedDateTime.now().format(DateTimeFormatter.ISO_INSTANT)))
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8" // Use the UTF-8 charset for Java compilation.
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        isDownloadSources = true
        isDownloadJavadoc = true
    }
}

class StringDelegate {
    operator fun getValue(thisRef: Project, property: KProperty<*>): String
        = thisRef.findProperty(property.name)?.toString() ?: error("Property '${property.name}' not found in gradle.properties")
}