# Buildscript Properties
kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

mapping_channel=official
mapping_version=1.21.1

# Environment Properties
mcVersion = 1.21.1
mcVersionRange = [1.21.1,)
neoForgedVersion = 21.1.219
neoForgedVersionRange = [21.1.0,)
parchmentVersion = 2024.11.17
parchmentMcVersion = 1.21.1
modLoaderVersionRange = [3.7.1,)

# Mod Properties
modId = examplemod
modName = Example Mod
modGroup = examplemod
modVersion = 1.0.0
modAuthors = Magic_Sweepy
modLicense = MIT License
modDescription = Example Scala Mod Template for Minecraft 1.21.1 Neoforged
modCredits =